import { createContext, useContext, useState, useMemo } from 'react';

// Define the shape of the context
interface LanguageContextType {
  language: 'es' | 'en';
  setLanguage: (language: 'es' | 'en') => void;
  t: (key: string, vars?: object) => string;
}

// Create the context with a default value
const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

// Translation dictionary
const translations: Record<string, Record<string, string>> = {
  es: {
    Home: 'Inicio',
    invest: 'Invertir',
    trade: 'P2P',
    philanthropy: 'Filantropía',
    billing: 'Facturación',
    create_project: 'Publica tu Proyecto',
    invest_market: 'Invest Market',
    discover_tokenized_opportunities: 'Descubre oportunidades de inversión tokenizadas',
    search: 'Buscar...',
    category: 'Categoría',
    all: 'Todos',
    real_estate: 'Real Estate',
    crypto: 'Crypto',
    startup: 'Startup',
    sort_by: 'Ordenar por',
    default: 'Defecto',
    price_asc: 'Precio: Menor a Mayor',
    price_desc: 'Precio: Mayor a Menor',
    roi_desc: 'ROI: Mayor a Menor',
    available: 'Disponible',
    sold_out: 'Agotado',
    expected_return: 'De Rentabilidad esperada en {currency} a {duration} meses',
    coming_soon: 'Próximamente',
    more_info: 'Más Info',
    // Investment data
    tokenized_apartments_title: 'Departamentos Pozo Tokenizados',
    tokenized_apartments_desc: 'Inversión en departamentos de lujo en zona premium con tokenización completa',
    crypto_fund_title: 'Fondo de Criptomonedas',
    crypto_fund_desc: 'Portfolio diversificado de criptomonedas principales con gestión profesional',
    tokenized_startup_title: 'Startup Tech Tokenizada',
    tokenized_startup_desc: 'Participación en startup de tecnología con gran potencial de crecimiento',
    // Create Project Page
    publish_new_project: 'Publicar Nuevo Proyecto de Inversión',
    fill_details_for_investors: 'Completa los detalles para que otros usuarios puedan invertir en tu proyecto.',
    project_name: 'Nombre del Proyecto',
    my_innovative_project: 'Mi Innovador Proyecto',
    project_description: 'Descripción del Proyecto',
    describe_your_project: 'Describe tu proyecto en detalle...',
    funding_goal_usd: 'Objetivo de Financiación (USD)',
    project_image_url: 'URL de la Imagen del Proyecto',
    project_image_url_placeholder: 'https://ejemplo.com/imagen-proyecto.jpg',
    token_symbol: 'Símbolo del Token (Ej: MYPROJ)',
    total_token_supply: 'Suministro Total de Tokens',
    publish_project_button: 'Publicar Proyecto',
    by_publishing_note: 'Al publicar, tu proyecto estará visible para posibles inversores.',
    project_submitted_alert: 'Proyecto enviado (simulado)! Revisa la consola para los datos.',
    // User Dropdown
    my_account: 'Mi cuenta',
    my_profile: 'Mi Perfil',
    my_investments: 'Mis Inversiones',
    my_benefits: 'Mis Beneficios',
    logout: 'Salir',
    // Trade Page
    p2p_market: 'Mercado P2P',
    trade_security_tokens: 'Intercambia security tokens de forma segura y eficiente.',
    filters: 'Filtros',
    search_by_name: 'Buscar por nombre...',
    all_categories: 'Todas las categorías',
    energy: 'Energía',
    venture_capital: 'Capital de Riesgo',
    collectibles: 'Coleccionables',
    newest: 'Más recientes',
    clear_filters: 'Limpiar Filtros',
    buy_tokens: 'Comprar Tokens',
    sell_my_tokens: 'Vender Mis Tokens',
    buy_now: 'Comprar Ahora',
    create_sell_offer: 'Crear una Oferta de Venta',
    publish_your_tokens: 'Publica tus tokens en el mercado para que otros los compren.',
    token_to_sell: 'Token a Vender',
    select_from_portfolio: 'Selecciona de tu portafolio',
    available_to_sell: 'disponibles',
    quantity: 'Cantidad',
    quantity_placeholder: 'Ej: 10',
    price_per_token_usd: 'Precio por Token (USD)',
    price_placeholder: 'Ej: 105.50',
    publish_sell_offer: 'Publicar Oferta de Venta',
    sell_offer_created: '¡Oferta de venta creada (simulado)!',
    buy_listing_simulated: '¡Has comprado (simulado) el listing {listingId}!',
    // Landing Page
    landing_beta_badge: 'Lanzamiento beta abierto — accedé hoy',
    landing_hero_title: 'Inversión tokenizada con seguridad y transparencia',
    landing_hero_desc: 'Investoken te ayuda a diversificar tu portafolio con activos tokenizados. Costos bajos, liquidez, y control total.',
    landing_demo_login: 'Demo Login',
    landing_explore_market: 'Explorar mercado',
    landing_no_hidden_costs: 'Sin costos ocultos. Cumplimiento y auditorías periódicas.',
    landing_metrics_title: 'Métricas clave',
    landing_volume: 'Volumen operado',
    landing_investors: 'Inversores registrados',
    landing_satisfaction: 'Satisfacción de usuarios',
    landing_support: 'Monitoreo y soporte',
    landing_why_choose: '¿Por qué elegir Investoken?',
    landing_why_desc: 'Plataforma diseñada para inversores que buscan transparencia, seguridad y control total sobre sus activos',
    landing_security_title: 'Seguridad garantizada',
    landing_security_desc: 'Tecnología blockchain para registrar cada operación con trazabilidad completa. Cumplimos criterios de la UIF, pertenecemos a la Cámara Argentina de Fintech y seguimos normas de seguridad estrictas.',
    landing_performance_title: 'Rendimiento y liquidez',
    landing_performance_desc: 'Acceso a oportunidades con mejor relación riesgo/retorno. Posibilidad de entrada y salida cuando lo necesites con mercado secundario activo.',
    landing_experience_title: 'Experiencia simple',
    landing_experience_desc: 'Interfaz intuitiva y moderna con soporte en español. Crea, gestiona y monitorea tu portafolio completo sin ningún tipo de fricción.',
    landing_testimonials_title: 'Lo que dicen nuestros usuarios',
    landing_testimonials_desc: 'Miles de inversores confían en Investoken para gestionar sus activos',
    landing_testimonial_1: 'Pude diversificar con tickets bajos y seguimiento en tiempo real. El retiro fue simple y transparente.',
    landing_testimonial_2: 'Las métricas y reportes me ayudaron a ajustar mi estrategia de inversión sin complicaciones.',
    landing_testimonial_3: 'Me gustó la transparencia y el soporte 24/7. Todo quedó claro desde el primer momento.',
    landing_trust_title: 'Confianza que se construye',
    landing_trust_desc: 'Diseñado con prácticas de seguridad líderes, verificación de identidad y monitoreo continuo para proteger tu inversión',
    landing_custody_title: 'Custodia segura',
    landing_custody_desc: 'Protección de activos con tecnología blockchain',
    landing_kyc_title: 'KYC/AML verificado',
    landing_kyc_desc: 'Cumplimiento y auditorías regulares',
    landing_support_title: 'Soporte 24/7',
    landing_support_desc: 'Asistencia dedicada cuando la necesites',
    landing_tokenized_assets: 'Activos tokenizados para diversificar tu portafolio',
    landing_tokenized_assets_desc: 'Invertí en activos tokenizados, proyectos de real estate, energía y fintech. Análisis en tiempo real, reportes y herramientas de trading para decisiones informadas.',
    landing_faq_title: 'Preguntas frecuentes',
    landing_faq_desc: 'Resolvemos tus dudas sobre inversión tokenizada',
    landing_faq_q1: '¿Qué es la inversión tokenizada?',
    landing_faq_a1: 'Es la representación digital de activos mediante tokens blockchain para facilitar el acceso, fraccionamiento y liquidez. Permite invertir en activos que tradicionalmente requerían grandes capitales.',
    landing_faq_q2: '¿Cómo empiezo a invertir?',
    landing_faq_a2: 'Crea tu cuenta en minutos, completa la verificación de identidad (KYC) y explora las oportunidades de inversión disponibles en el mercado. Nuestro equipo te guiará en cada paso.',
    landing_faq_q3: '¿Puedo retirar mi inversión cuando quiera?',
    landing_faq_a3: 'Depende del activo específico. Muchos ofrecen ventanas de liquidez programadas o acceso al mercado secundario donde puedes vender tus tokens a otros inversores.',
    landing_cta_title: 'Empezá hoy con Investoken',
    landing_cta_desc: 'Probá la plataforma gratis y descubre cómo simplificar tu inversión en activos tokenizados',
    landing_view_analytics: 'Ver analíticas',
    landing_join_investors: 'Únete a más de 10,000 inversores que confían en Investoken',
    landing_investment_opportunities: 'Oportunidades de Inversión',
    landing_investment_opportunities_desc: 'Acceso a proyectos de inversión tokenizados. Participa en grandes oportunidades con pequeñas inversiones.',
    // Investments Page
    investments_page_title: 'Mis Inversiones',
    investments_page_desc: 'Gestiona y monitorea tus activos tokenizados',
    total_value: 'Valor Total',
    change_24h: 'Cambio 24h',
    average_roi: 'ROI Promedio',
    active_assets: '{count} activos',
    expected_annual_return: 'Retorno anual esperado',
    your_tokens: 'Tus Tokens',
    token_list_desc: 'Listado de todos los activos que posees',
    asset: 'Activo',
    unit_price: 'Precio Unitario',
    total_value_col: 'Valor Total',
    change_24h_col: 'Cambio 24h',
    annual_roi_col: 'ROI Anual',
    status_col: 'Estado',
    download_report: 'Descargar Reporte',
    invest_more: 'Invertir Más',
    sell_token: 'Vender',
  },
  en: {
    Home: 'Home',
    invest: 'Invest',
    trade: 'Trade',
    philanthropy: 'Philanthropy',
    billing: 'Billing',
    create_project: 'Publish Your Project',
    invest_market: 'Invest Market',
    discover_tokenized_opportunities: 'Discover tokenized investment opportunities',
    search: 'Search...',
    category: 'Category',
    all: 'All',
    real_estate: 'Real Estate',
    crypto: 'Crypto',
    startup: 'Startup',
    sort_by: 'Sort by',
    default: 'Default',
    price_asc: 'Price: Low to High',
    price_desc: 'Price: High to Low',
    roi_desc: 'ROI: High to Low',
    available: 'Available',
    sold_out: 'Sold Out',
    expected_return: 'Of expected return in {currency} at {duration} months',
    coming_soon: 'Coming Soon',
    more_info: 'More Info',
    // Investment data
    tokenized_apartments_title: 'Tokenized Apartments',
    tokenized_apartments_desc: 'Investment in luxury apartments in a premium area with complete tokenization',
    crypto_fund_title: 'Cryptocurrency Fund',
    crypto_fund_desc: 'Diversified portfolio of major cryptocurrencies with professional management',
    tokenized_startup_title: 'Tokenized Tech Startup',
    tokenized_startup_desc: 'Participation in a technology startup with great growth potential',
    // Create Project Page
    publish_new_project: 'Publish New Investment Project',
    fill_details_for_investors: 'Complete the details so other users can invest in your project.',
    project_name: 'Project Name',
    my_innovative_project: 'My Innovative Project',
    project_description: 'Project Description',
    describe_your_project: 'Describe your project in detail...',
    funding_goal_usd: 'Funding Goal (USD)',
    project_image_url: 'Project Image URL',
    project_image_url_placeholder: 'https://example.com/project-image.jpg',
    token_symbol: 'Token Symbol (e.g., MYPROJ)',
    total_token_supply: 'Total Token Supply',
    publish_project_button: 'Publish Project',
    by_publishing_note: 'By publishing, your project will be visible to potential investors.',
    project_submitted_alert: 'Project submitted (simulated)! Check the console for the data.',
    // User Dropdown
    my_account: 'My Account',
    my_profile: 'My Profile',
    my_investments: 'My Investments',
    my_benefits: 'My Benefits',
    logout: 'Logout',
    // Trade Page
    p2p_market: 'P2P Market',
    trade_security_tokens: 'Trade security tokens securely and efficiently.',
    filters: 'Filters',
    search_by_name: 'Search by name...',
    all_categories: 'All categories',
    energy: 'Energy',
    venture_capital: 'Venture Capital',
    collectibles: 'Collectibles',
    newest: 'Newest',
    clear_filters: 'Clear Filters',
    buy_tokens: 'Buy Tokens',
    sell_my_tokens: 'Sell My Tokens',
    buy_now: 'Buy Now',
    create_sell_offer: 'Create Sell Offer',
    publish_your_tokens: 'Publish your tokens on the market for others to buy.',
    token_to_sell: 'Token to Sell',
    select_from_portfolio: 'Select from your portfolio',
    available_to_sell: 'available',
    quantity: 'Quantity',
    quantity_placeholder: 'e.g., 10',
    price_per_token_usd: 'Price per Token (USD)',
    price_placeholder: 'e.g., 105.50',
    publish_sell_offer: 'Publish Sell Offer',
    sell_offer_created: 'Sell offer created (simulated)!',
    buy_listing_simulated: 'You have bought (simulated) listing {listingId}!',
    // Landing Page
    landing_beta_badge: 'Open beta launch — get access today',
    landing_hero_title: 'Tokenized investing with security and transparency',
    landing_hero_desc: 'Investoken helps you diversify your portfolio with tokenized assets. Low costs, liquidity, and full control.',
    landing_demo_login: 'Demo Login',
    landing_explore_market: 'Explore market',
    landing_no_hidden_costs: 'No hidden fees. Compliance and regular audits.',
    landing_metrics_title: 'Key metrics',
    landing_volume: 'Trading volume',
    landing_investors: 'Registered investors',
    landing_satisfaction: 'User satisfaction',
    landing_support: 'Monitoring and support',
    landing_why_choose: 'Why choose Investoken?',
    landing_why_desc: 'Platform designed for investors seeking transparency, security, and full control of their assets',
    landing_security_title: 'Guaranteed security',
    landing_security_desc: 'Blockchain technology to record every operation with complete traceability. We comply with UIF requirements, are members of the Argentine Fintech Chamber, and follow strict security standards.',
    landing_performance_title: 'Performance and liquidity',
    landing_performance_desc: 'Access to opportunities with better risk/return ratios. Ability to enter and exit whenever needed with an active secondary market.',
    landing_experience_title: 'Simple experience',
    landing_experience_desc: 'Intuitive and modern interface with Spanish support. Create, manage, and monitor your complete portfolio without friction.',
    landing_testimonials_title: 'What our users say',
    landing_testimonials_desc: 'Thousands of investors trust Investoken to manage their assets',
    landing_testimonial_1: 'I was able to diversify with low minimum investments and real-time tracking. Withdrawal was simple and transparent.',
    landing_testimonial_2: 'The metrics and reports helped me adjust my investment strategy without complications.',
    landing_testimonial_3: 'I liked the transparency and 24/7 support. Everything was clear from the start.',
    landing_trust_title: 'Trust that is built',
    landing_trust_desc: 'Designed with leading security practices, identity verification, and continuous monitoring to protect your investment',
    landing_custody_title: 'Secure custody',
    landing_custody_desc: 'Asset protection with blockchain technology',
    landing_kyc_title: 'KYC/AML verified',
    landing_kyc_desc: 'Compliance and regular audits',
    landing_support_title: '24/7 Support',
    landing_support_desc: 'Dedicated assistance when you need it',
    landing_tokenized_assets: 'Tokenized assets to diversify your portfolio',
    landing_tokenized_assets_desc: 'Invest in tokenized assets, real estate projects, energy, and fintech. Real-time analysis, reports, and trading tools for informed decisions.',
    landing_faq_title: 'Frequently asked questions',
    landing_faq_desc: 'We answer your questions about tokenized investing',
    landing_faq_q1: 'What is tokenized investing?',
    landing_faq_a1: 'It is the digital representation of assets through blockchain tokens to facilitate access, fractionalization, and liquidity. It allows investing in assets that traditionally required large capital amounts.',
    landing_faq_q2: 'How do I start investing?',
    landing_faq_a2: 'Create your account in minutes, complete identity verification (KYC), and explore available investment opportunities in the market. Our team will guide you at every step.',
    landing_faq_q3: 'Can I withdraw my investment whenever I want?',
    landing_faq_a3: 'It depends on the specific asset. Many offer scheduled liquidity windows or access to the secondary market where you can sell your tokens to other investors.',
    landing_cta_title: 'Start today with Investoken',
    landing_cta_desc: 'Try the platform for free and discover how to simplify your tokenized asset investing',
    landing_view_analytics: 'View analytics',
    landing_join_investors: 'Join over 10,000 investors who trust Investoken',
    landing_investment_opportunities: 'Investment Opportunities',
    landing_investment_opportunities_desc: 'Access to tokenized investment projects. Participate in great opportunities with small investments.',
    // Investments Page
    investments_page_title: 'My Investments',
    investments_page_desc: 'Manage and monitor your tokenized assets',
    total_value: 'Total Value',
    change_24h: '24h Change',
    average_roi: 'Average ROI',
    active_assets: '{count} assets',
    expected_annual_return: 'Expected annual return',
    your_tokens: 'Your Tokens',
    token_list_desc: 'List of all assets you own',
    asset: 'Asset',
    unit_price: 'Unit Price',
    total_value_col: 'Total Value',
    change_24h_col: '24h Change',
    annual_roi_col: 'Annual ROI',
    status_col: 'Status',
    download_report: 'Download Report',
    invest_more: 'Invest More',
    sell_token: 'Sell',
  },
};

// Create the provider component
export function LanguageProvider({ children }: { children: React.ReactNode }) {
  const [language, setLanguage] = useState<'es' | 'en'>('es');

  const t = (key: string, vars: object = {}) => {
    let translation = translations[language][key] || key;
    for (const [varKey, varValue] of Object.entries(vars)) {
      translation = translation.replace(`{${varKey}}`, String(varValue));
    }
    return translation;
  };

  const value = useMemo(() => ({
    language,
    setLanguage,
    t,
  }), [language]);

  return (
    <LanguageContext.Provider value={value}>
      {children}
    </LanguageContext.Provider>
  );
}

// Create a custom hook for using the context
export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
}
