export const marketProjects = [
  { id: '1', projectName: 'Eco-Friendly Housing', tokenSymbol: 'ECOH', quantity: 100, pricePerToken: 105, seller: '0xabc...', image: 'https://res.cloudinary.com/dhacybdxf/image/upload/v1762299810/edificio_qhi0ri.png', category: 'Real Estate', marketUrl: '/invest/project1', paymentMethods: ['Transferencia Bancaria', 'MercadoPago'], totalDuration: '24 meses' },
  { id: '2', projectName: 'Fondo de Criptomonedas', tokenSymbol: 'CRYF', quantity: 50, pricePerToken: 50, seller: '0xdef...', image: 'https://res.cloudinary.com/dhacybdxf/image/upload/v1762299809/ethereum_vs8k4y.png', category: 'Crypto', marketUrl: '/invest/project2', paymentMethods: ['Transferencia Bancaria', 'USDT'], totalDuration: '12 meses' },
  { id: '3', projectName: 'Campo Santa Lucía – Zona Núcleo', tokenSymbol: 'CSL', quantity: 200, pricePerToken: 125, seller: '0xghi...', image: 'https://via.placeholder.com/800x400?text=Campo+Santa+Lucia', category: 'Real Estate', marketUrl: '/invest/project3', paymentMethods: ['Transferencia Bancaria', 'USDT'], totalDuration: '36 meses' },
  { id: '4', projectName: 'Tokenización de Ganado – Vaca Alfa', tokenSymbol: 'VA', quantity: 750, pricePerToken: 80, seller: '0xjkl...', image: 'https://via.placeholder.com/800x400?text=Vaca+Alfa', category: 'Real Estate', marketUrl: '/invest/project4', paymentMethods: ['Transferencia Bancaria', 'USDT'], totalDuration: '10 meses' },
  { id: '5', projectName: 'Polo Horse Token – "Embajador"', tokenSymbol: 'PHT', quantity: 1000, pricePerToken: 50, seller: '0xmno...', image: 'https://via.placeholder.com/800x400?text=Polo+Horse+Embajador', category: 'Real Estate', marketUrl: '/invest/project5', paymentMethods: ['Transferencia Bancaria', 'USDT'], totalDuration: '18 meses' },
  { id: '6', projectName: 'Recital Tokenizado – "LUNA EN VIVO 2025"', tokenSymbol: 'LUNA', quantity: 2500, pricePerToken: 100, seller: '0xpqr...', image: 'https://via.placeholder.com/800x400?text=Luna+En+Vivo+2025', category: 'Entretenimiento', marketUrl: '/invest/project6', paymentMethods: ['Transferencia Bancaria', 'USDT'], totalDuration: '6 meses' },
  { id: '7', projectName: 'Investoken – Seed Round', tokenSymbol: 'INV', quantity: 10, pricePerToken: 50000, seller: '0xstu...', image: 'https://via.placeholder.com/800x400?text=Investoken+Startup', category: 'Startup', marketUrl: '/invest/project7', paymentMethods: ['Transferencia Bancaria', 'USDT', 'USDC'], totalDuration: '36 meses' },
];
